### ISSUE TITLE
recording next meeting?

### ISSUE THREAD

**Issue by taddeimania** [dsmjs/dsmjs.github.io#13]
i'm very interested in hearing from @toranb use of redux in ember.  Is he or anyone on the ground planning on recording it or streaming it?

**Comment by toranb** [comment]
I'm planning to record a screencast version of the content myself next week and I'll throw that up on Vimeo. I'll be sure to post a link here for anyone that is curious :)

**Comment by toranb** [comment]
@taddeimania here is the full blown recording of my talk :)

https://vimeo.com/166199795
