### ISSUE TITLE
add a CONTRIBUTING.md

### ISSUE THREAD

**Issue by travi** [dsmjs/dsmjs.github.io#30]
the contribution instructions in the `README.md` are out of date, so this would be a good time to update to leverage github's [somewhat special treatment](https://github.com/blog/1184-contributing-guidelines) of the `CONTRIBUTING.md`

**Comment by travi** [comment]
http://makeapullrequest.com

**Comment by crolek** [comment]
I like this idea of linking to makeapullrequest.com :D

**Comment by toranb** [comment]
http ?? I assumed 2017 was the year of all things https :)

**Comment by travi** [comment]
issue and pull-request templates would be valuable as well: https://github.com/blog/2111-issue-and-pull-request-templates
